const contractType = require('../controllers/contractType.controller')
const router = require('express').Router()
router.post('/',contractType.insertContractType)
router.get('/',contractType.getAllContractType)
router.get('/:id/:lang',contractType.getByIdContractType)
router.get('/:id',contractType.getDataById)
router.delete('/delete/:id',contractType.deleteContractById)
router.post('/fill/:id',contractType.fillContract)
router.put('/updateImage/:id',contractType.updateContractImage)
router.post("/ChangeStatusInContract",contractType.ChangeStatusInContract)
//router.get("/getContractById/:id/:lang",contractType.getContractById)
router.post("/concatImages",contractType.concatImages)
router.post("/addAnswersToAnswerTable",contractType.addAnswersToAnswerTable)
module.exports = router;